version: "3"
services:
    db:
        image: store/oracle/database-enterprise:12.2.0.1
        ports:
            - "15215:1521"
        volumes:
            - /data/Test12c:/ORCL

    redis:
        image: redis
#        ports:
#            - "16379:6379"


    worker:
        image: chizhang/daggoo
        # build: ./worker
        command: /bin/bash start.sh
        tty: true
        volumes:
            - /data:/data
        sysctls:
            net.core.somaxconn: 4096
#        ports:
#            - "8000:8000"
        depends_on:
            - db
            - redis
            - mongo
        links:
            - db
            - redis
            - mongo
         networks:
             - outside

    web:
        image: chizhang/nginx
        # build: ./web
        volumes:
            - /data/var/log:/var/log
            - /data/www:/data/www
        ports:
            - "80:80"
        links:
            - worker

    neo4j:
        image: neo4j
        volumes:
            - /data/neo4j:/data
        ports:
            - "17474:7474"

    es:
        image: elasticsearch:6.5.4
        volumes:
            - /data/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9003:9300"
            - "9002:9200"
        sysctls:
            vm.max_map_count: 262144
        networks:
            - somenetwork

    mongo:
        image: mongo
        restart: always
        volumes:
            - /data/mongodb:/data/db
        ports:
            - "27077:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: daggoo
            MONGO_INITDB_ROOT_PASSWORD: daggoo

    rabbitmq:
        image: rabbitmq
        restart: always
        volumes:
            - /data/rabbitmq/log:/var/log/rabbitmq
            - /data/rabbitmq/data:/var/lib/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: databao
            RABBITMQ_DEFAULT_PASS: databao123
networks:
    outside:
        external: true
