version: "3"
services:
    db:
        image: chizhang/oracle-ee-11g
        ports:
            - "15215:1521"
        volumes:
            - /data/oracle/data:/u01/app/oracle

    redis:
        image: redis
#        ports:
#            - "16379:6379"


    worker:
        image: chizhang/daggoo
        # build: ./worker
        command: /bin/bash start.sh
        tty: true
        volumes:
            - /data:/data
        sysctls:
            net.core.somaxconn: 4096
#        ports:
#            - "8000:8000"
        depends_on: 
            - db 
            - redis 
        links:
            - db 
            - redis

    web:
        images: chizhang/nginx
        # build: ./web
        volumes:
            - /data/var/log:/var/log
            - /data/www:/data/www
        ports:
            - "80:80"
        links:
            - worker

    neo4j:
        image: neo4j
        volumes:
            - /data/neo4j:/data
        ports:
            - "17474:7474"

    es:
        image: elasticsearch:6.5.4
        volumes:
            - /data/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9003:9300"
            - "9002:9200"
        sysctls:
            vm.max_map_count: 262144
        networks:
            - somenetwork

    mongo:
        image: mongo
        volumes:
            - /data/mongodb:/data/db
        ports:
            - "27077:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: daggoo
            MONGO_INITDB_ROOT_PASSWORD: daggoo
networks:
    somenetwork:
